---
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@main"
    permissions:
      contents: write
    with:
      enable_draft: ${{ github.event_name == 'pull_request' }}

  heimdallr:
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@main"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
